---
# local.yml is used for pull-based Ansible setup.

- hosts: localhost
  user: root
  connection: local
  tasks:
     - name: just check if local is updated.
       action: shell echo `date` "Hello Ansible."  >> /var/log/ansible.log

